dist: trusty 
sudo: required

language: cpp

os:
  - linux
compiler: 
  - gcc
addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck
before_script:
  - mkdir build && cd build
  - cmake ..
  - make
  - cp ../tests/test10k.bin

script:
  - valgrind --track-origins=yes --leak-check=full ./test_static
  - valgrind --track-origins=yes --leak-check=full ./test_dynamic
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./test_static
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./test_dynamic
  - ./stress_test
  - cd "${TRAVIS_BUILD_DIR}"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  