dist: trusty 
sudo: required

language: cpp

os:
  - linux
compiler: 
  - gcc
addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck
before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cmake .
  - make

script:
  - valgrind --track-origins=yes --leak-check=full ./test_static
  - valgrind --track-origins=yes --leak-check=full ./test_dynamic
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./test_static
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./test_dynamic
  - ./stress_test
  - cd "${TRAVIS_BUILD_DIR}"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  